# Generated by Django 3.2.15 on 2022-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_coupon_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='backend.Coupon'),
        ),
    ]
