# Generated by Django 3.2.15 on 2022-08-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paywithpaystack',
            old_name='date_payed',
            new_name='date_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='backend.paywithpaystack'),
        ),
    ]
